version: "1.0"

services:

  # app:
  #   build:
  #     context: ./
  #     dockerfile: docker/app/Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: always

  db:
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/paytaxi


volumes:
  db_data:

